### PR TITLE
Virtual filesystem support

### PR DESCRIPTION
**Pull request by BeastLe9enD**
Extended fast_obj_read_with_callbacks function to load from virtual file systems :)

### CODE REVIEW

**Comment by thisistherk** [comment]
Awesome - thanks!  Few little nits:
- it needs a #include <stdlib.h> for size_t
- nullptr is a C++ thing, needs to compile with C too
- could you fix the unused parameter warnings in file_open etc (just change the user_data param to something like `void* /*user_data*/` should do it I think)
- could you fix the indents in the new callbacks struct to match the rest of the code?

`clang -Wall -Wextra fast_obj.c` if your on Mac/Linux should point most of them out :)

**Comment by BeastLe9enD** [comment]
Ok, fixed it, also noticed that there is a warning with fopen on Windows which forces you to use Windows-specific fopen_s. Fixed it through _CRT_SECURE_NO_WARNINGS, hope thats ok !:)

**Comment by thisistherk** [comment]
Thanks!  Couple of further tiny things, sorry!  Think we should probably not define _CRT_SECURE_NO_WARNINGS.  Generally I think we should write code to avoid warnings where possible, but we probably shouldn't actually turn warnings off - leave that up to the user :)

Also need to tweak the unused var stuff a tiny bit.  The variable declarations need to go at the top to work with C89 - so like:
```
{
    FILE* f;
    (void)(user_data);
```

**Comment by BeastLe9enD** [comment]
its fine!:) Incidentally, did not know that the variables must first be declared in C89

**Comment by thisistherk** [comment]
Brilliant - thanks!

**Pull request merged**
