### PR TITLE
added support for colored vertices (issue #28)

### PR DESCRIPTION
**Pull request by maxrigout**
I've added support for parsing colored vertex.

I've included the parsing in the parse_vertex function since in the obj, the data is on the same line as the position (v x y z r g b).
In the case there's no data, it would add 1s. I've considered adding a flag indicating whether or not the obj file has vertex colors, but then I feel like I'd have to check cases when only some vertices have colors, or if it's missing color components (am I over thinking this?)

It's my first PR so I have little knowledge of this project's standards. Feel free to let me know your thoughts and if I should keep working on this. Thanks

### CODE REVIEW

**Comment by thisistherk** [comment]
That looks great, thanks!  I think you're right that adding a flag gets complicated with all the corner cases, but I wonder if it's worth putting it behind a `#define FAST_OBJ_ENABLE_COLOURS` or something?  Just thinking that not everyone needs colour support, so it'd be nice to have it as an optional thing that people can turn on if they need it...

**Comment by zeux** [comment]
When enabled (whether unconditionally or via a define), this change would increase the memory fairly substantially: positions would now cost 48 bytes instead of 24 bytes, and face indices would cost 16 bytes instead of 12 bytes.

In both cases the increase feels unnecessary assuming the file doesn't carry color information. `.c` field feels redundant as it is always equal to `.p`, and `colors` array could be filled lazily upon encountering the color (if you encounter a color, pad colors array with `1` until the current size of position array).

There is also the performance impact of calling `parse_float`; it could be mitigated by checking if the next character is a `\r` or \`n` after parsing the last position float, and only trying to parse colors if it's not (or alternatively checking for space or tab).

**Comment by thisistherk** [comment]
Yeah, that makes sense - I think that's a much better way of doing it than hiding it behind a define...

**Comment by maxrigout** [comment]
I've opted to leave the FAST_OBJ_ENABLE_COLOURS define to disable the color parsing and avoid the overhead of the extra allocations. I didn't find any significant performance loss when parsing an obj without vertex colors.
I've implemented the lazy fill as @zeux suggested, but for some reason, I was getting much worse performance on my machine when parsing a file with vertex colors (even compared to tiny obj loader). It might be specific to my machine so I left it in. It might also be that I didn't implement this right, tbh it was my first time implementing something like this.
The main change from the previous PR is that I'm no longer storing default values, but instead storing each color value that we encounter. Then I store in the `vertex_color_index` the index of that color for this specific vertex position. This gives meaning to `.c` as it's no longer the same as `.p`

I'll need to do more testing to find out what's the performance loss when parsing vertex colors, but I wanted to get it out there to see if there's anything else I should change.

Let me know your thoughts.

**Comment by thisistherk** [comment]
I think you can probably simplify it quite a bit - the loop in `parse_vertex` could probably be something more like:
```
    ptr = skip_whitespace(ptr);
    if (!is_newline(*ptr))
    {
        /* Fill any gap in the colors array */
        vsz = array_size(data->mesh->vertices);
        csz = array_size(data->mesh->colors);
        for (ii = csz; ii < vsz - 3; ii++)
             array_push(data->mesh->colors, 1.0f);
        
        /* Add the color for this vertex */
        for (ii = 0; ii < 3; ++ii)
        {
            ptr = parse_float(ptr, &c);
            array_push(data->mesh->colors, c);
        }
    }
```
Then you'd need a similar bit of code at the end to ensure the colours array is either empty, or the same size as the vertices array.  On output the colours array is then either `NULL` if there are no colours, or indexed via `.p`.

Usual case is probably that there are either no colours, so there's no extra memory overhead and the only extra code is the `skip_whitespace` & `is_newline` which ought to be fairly insignificant.  Or that every vertex has a colour, in which case the loop that fills the gaps will almost never do anything, so you'd just have the extra overhead of parsing the floats and the per-vertex colour array.  Should (I think!) still handle the in-between cases where only some vertices have colours too though.

Typed all that into github without trying to compile anything, so it's entirely likely I've missed something, but hopefully should give you the rough idea :)

Thank you for tackling this btw!

**Comment by maxrigout** [comment]
yeah I see what you're saying. Imo it feels a little weird to access color data through the `.p` but at least there's no overhead from the color parsing component when the obj file doesn't have a color component. Thank you for the feedback :)

**Comment by zeux** [comment]
I've tested the latest changes in gltfpack (https://github.com/zeux/meshoptimizer/pull/587) and they seem to work fine.

One of the files in my test data set had 4-float position data:

```
# humanoid_quad.obj
# created by TEC_TO_OBJ.F90.
v 3.25000 -2.48000 14.0000 1.00000
```

I don't know how prevalent this is; the result of this is that we parse all vertices as if they have color (1, 0, 0). We could work around this by checking if we have two floats to parse if need be, e.g. something like

```
float r, g, b;
ptr = parse_float(ptr, &r);
ptr = skip_whitespace(ptr);
if (is_newline(*ptr)) { return ptr; }
ptr = parse_float(ptr, &g);
ptr = parse_float(ptr, &b);
array_push(data->mesh->colors, r);
array_push(data->mesh->colors, g);
array_push(data->mesh->colors, b);
```

... or we could ignore this problem for now, as it's possible that the file I have is unique somehow.

**Comment by thisistherk** [comment]
I think we can ignore that for now if it's not causing a problem - found a version of the `TEC_TO_OBJ` fortran source [here](https://people.math.sc.edu/Burkardt/f_src/tec_to_obj/tec_to_obj.f90), which has a comment:
```
!  V: vertex coordinates.
!  For some reason, a fourth "coordinate" may be recommended.
!  What is its meaning?
```
So seems possible it's just a misunderstanding on the part of whoever wrote that...

**Pull request merged**
